# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-15 06:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='area',
            name='update_time',
        ),
    ]
