# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-25 10:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_goods_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subs', to='goods.GoodsCategory', verbose_name='上级类别'),
        ),
    ]
